kafka:
  brokers:
    - "localhost:9092"
  group_id: "my-consumer-group"
  topics:
    - "topic1"
    - "topic2"
    - "topic3"
  auto_offset_reset: "latest"  # or "earliest"
  session_timeout: 10s
  heartbeat_interval: 3s
  max_poll_interval: 5m
  max_poll_records: 500
  security:
    enabled: false
    username: ""
    password: ""
    ca_file: ""
    cert_file: ""
    key_file: ""
    skip_verify: false 